// Mocks generated by Mockito 5.4.4 from annotations
// in suez_canal_assignment/test/mocks/mock_nutrition_details_usecase.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:suez_canal_assignment/core/params/ingredient_request_params.dart'
    as _i6;
import 'package:suez_canal_assignment/core/resources/data_state.dart' as _i2;
import 'package:suez_canal_assignment/data/models/data_response_model.dart'
    as _i5;
import 'package:suez_canal_assignment/domain/usecases/nutrition_details_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NutritionDetailsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionDetailsUsecase extends _i1.Mock
    implements _i3.NutritionDetailsUsecase {
  MockNutritionDetailsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i5.DataResponseModel>> call(
          {_i6.IngredientRequestParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.DataResponseModel>>.value(
            _FakeDataState_0<_i5.DataResponseModel>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.DataResponseModel>>);
}
